name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Build Image
      run: |
        docker build -t "${{ DOCKERHUB_USER }}/petclinic:${{ github.sha }}" .
        docker images

    - name: Docker Login
      run: docker login -u ${{ DOCKERHUB_USER }} -p ${{ DOCKERHUB_PASS }}

    - name: Docker Push
      run: docker push ${{ DOCKERHUB_USER }}/petclinic:${{ github.sha }}
